# Generated by Django 5.1.7 on 2025-03-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('menu', models.CharField(choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg')], max_length=8)),
                ('capacity', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
