# Generated by Django 5.1.7 on 2025-03-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_add_room_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['category', 'location']},
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='menu',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg')], max_length=10),
        ),
    ]
