# Generated by Django 5.1.7 on 2025-03-30 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpverification'),
        ('payments', '0001_initial'),
        ('rooms', '0004_alter_room_created_at_alter_room_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.student'),
        ),
    ]
