# Generated by Django 5.1.7 on 2025-03-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_status',
            field=models.CharField(choices=[('No Request', 'No Request'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Failed', 'Failed')], default='No Request', max_length=15),
        ),
    ]
